/**
 * Language metadata - all supported languages with flags and names
 * Organized for readability
 */

import type { Language, LanguageMeta } from "./types";

export const ANCIENT_CODES: string[] = [
  "hit",
  "xur",
  "txr",
  "sux",
  "xpg",
  "xib",
  "elx",
  "phn",
  "lyd",
  "lyc",
  "egy",
  "sa",
  "akk",
  "uga",
  "peo",
  "xhu",
  "gmy",
  "cu",
  "got",
  "ang",
  "non",
  "xcl",
  "otk",
  "pal",
  "grc",
  "ave",
];

export const languages: LanguageMeta[] = [
  { code: "en" as Language, name: "English", flag: "🇬🇧" },
  { code: "es" as Language, name: "Español", flag: "🇪🇸" },
  { code: "ca" as Language, name: "Català", flag: "🇦🇩" },
  { code: "af" as Language, name: "Afrikaans", flag: "🇿🇦" },
  { code: "de" as Language, name: "Deutsch", flag: "🇩🇪" },
  { code: "nl" as Language, name: "Nederlands", flag: "🇳🇱" },
  { code: "it" as Language, name: "Italiano", flag: "🇮🇹" },
  { code: "tr" as Language, name: "Türkçe", flag: "🇹🇷" },
  { code: "ru" as Language, name: "Русский", flag: "🇷🇺" },
  { code: "uk" as Language, name: "Українська", flag: "🇺🇦" },
  { code: "pl" as Language, name: "Polski", flag: "🇵🇱" },
  { code: "pt" as Language, name: "Português", flag: "🇵🇹" },
  { code: "ka" as Language, name: "ქართული", flag: "🇬🇪" },
  { code: "az" as Language, name: "Azərbaycanca", flag: "🇦🇿" },
  { code: "hy" as Language, name: "Հայերեն", flag: "🇦🇲" },
  { code: "zh" as Language, name: "中文", flag: "🇨🇳" },
  { code: "fa" as Language, name: "فارسی", flag: "🇮🇷" },
  { code: "ja" as Language, name: "日本語", flag: "🇯🇵" },
  { code: "fr" as Language, name: "Français", flag: "🇫🇷" },
  { code: "id" as Language, name: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "vi" as Language, name: "Tiếng Việt", flag: "🇻🇳" },
  { code: "ms" as Language, name: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "el" as Language, name: "Ελληνικά", flag: "🇬🇷" },
  { code: "fy" as Language, name: "Frysk", flag: "🇳🇱" },
  { code: "ro" as Language, name: "Română", flag: "🇷🇴" },
  { code: "ar" as Language, name: "العربية", flag: "🇸🇦" },
  { code: "ku" as Language, name: "Kurdî", flag: "🇮🇶" },
  { code: "he" as Language, name: "עברית", flag: "🇮🇱" },
  { code: "yi" as Language, name: "ייִדיש", flag: "🇮🇱" },
  { code: "lad" as Language, name: "Ladino", flag: "🇮🇱" },
  { code: "sr" as Language, name: "Српски", flag: "🇷🇸" },
  { code: "kk" as Language, name: "Қазақша", flag: "🇰🇿" },
  { code: "crh" as Language, name: "Qırımtatarca", flag: "🇺🇦" },
  { code: "oc" as Language, name: "Occitan", flag: "🇫🇷" },
  { code: "cy" as Language, name: "Cymraeg", flag: "🇬🇧" },
  { code: "eu" as Language, name: "Euskara", flag: "🇪🇸" },
  { code: "qu" as Language, name: "Runa Simi", flag: "🇵🇪" },
  { code: "eo" as Language, name: "Esperanto", flag: "🌍" },
  { code: "rue" as Language, name: "Русиньскый", flag: "🇸🇰" },
  { code: "hi" as Language, name: "हिन्दी", flag: "🇮🇳" },
  { code: "la" as Language, name: "Latina", flag: "🇻🇦" },
  { code: "rm" as Language, name: "Rumantsch", flag: "🇨🇭" },
  { code: "gsw" as Language, name: "Schwiizertüütsch", flag: "🇨🇭" },
  { code: "be" as Language, name: "Беларуская", flag: "🇧🇾" },
  { code: "ab" as Language, name: "Аҧсуа", flag: "🇬🇪" },
  { code: "os" as Language, name: "Ирон", flag: "🇷🇺" },
  { code: "gl" as Language, name: "Galego", flag: "🇪🇸" },
  { code: "uz" as Language, name: "Oʻzbekcha", flag: "🇺🇿" },
  { code: "hr" as Language, name: "Hrvatski", flag: "🇭🇷" },
  { code: "val" as Language, name: "Valencià", flag: "🇪🇸" },
  { code: "mk" as Language, name: "Македонски", flag: "🇲🇰" },
  { code: "bg" as Language, name: "Български", flag: "🇧🇬" },
  { code: "hu" as Language, name: "Magyar", flag: "🇭🇺" },
  { code: "fi" as Language, name: "Suomi", flag: "🇫🇮" },
  { code: "no" as Language, name: "Norsk", flag: "🇳🇴" },
  { code: "is" as Language, name: "Íslenska", flag: "🇮🇸" },
  { code: "sv" as Language, name: "Svenska", flag: "🇸🇪" },
  { code: "da" as Language, name: "Dansk", flag: "🇩🇰" },
  { code: "fo" as Language, name: "Føroyskt", flag: "🇫🇴" },
  { code: "nah" as Language, name: "Nahuatl", flag: "🇲🇽" },
  { code: "tok" as Language, name: "Toki Pona", flag: "🌐" },
  { code: "ast" as Language, name: "Asturianu", flag: "🇪🇸" },
  { code: "an" as Language, name: "Aragonés", flag: "🇪🇸" },
  { code: "ga" as Language, name: "Gaeilge", flag: "🇮🇪" },
  { code: "gd" as Language, name: "Gàidhlig", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { code: "kw" as Language, name: "Kernewek", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { code: "cv" as Language, name: "Чăвашла", flag: "🇷🇺" },
  { code: "tt" as Language, name: "Татарча", flag: "🇷🇺" },
  { code: "krl" as Language, name: "Karjala", flag: "🇫🇮" },
  { code: "scn" as Language, name: "Sicilianu", flag: "🇮🇹" },
  { code: "co" as Language, name: "Corsu", flag: "🇫🇷" },
  { code: "zgh" as Language, name: "ⵜⴰⵎⴰⵣⵉⵖⵜ", flag: "🇲🇦" },
  { code: "ti" as Language, name: "ትግርኛ", flag: "🇪🇷" },
  { code: "sw" as Language, name: "Kiswahili", flag: "🇹🇿" },
  { code: "zu" as Language, name: "isiZulu", flag: "🇿🇦" },
  { code: "am" as Language, name: "አማርኛ", flag: "🇪🇹" },
  { code: "sl" as Language, name: "Slovenščina", flag: "🇸🇮" },
  { code: "sk" as Language, name: "Slovenčina", flag: "🇸🇰" },
  { code: "lt" as Language, name: "Lietuvių", flag: "🇱🇹" },
  { code: "lv" as Language, name: "Latviešu", flag: "🇱🇻" },
  { code: "et" as Language, name: "Eesti", flag: "🇪🇪" },
  { code: "jv" as Language, name: "Basa Jawa", flag: "🇮🇩" },
  { code: "su" as Language, name: "Basa Sunda", flag: "🇮🇩" },
  { code: "ta" as Language, name: "தமிழ்", flag: "🇮🇳" },
  { code: "kn" as Language, name: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "ur" as Language, name: "اردو", flag: "🇵🇰" },
  { code: "ps" as Language, name: "پښتو", flag: "🇦🇫" },
  { code: "nur" as Language, name: "Nuristani", flag: "🇦🇫" },
  { code: "pcm" as Language, name: "Nigerian Pidgin", flag: "🇳🇬" },
  { code: "ht" as Language, name: "Kreyòl Ayisyen", flag: "🇭🇹" },
  { code: "pap" as Language, name: "Papiamentu", flag: "🇨🇼" },
  { code: "hit" as Language, name: "𒉈𒅆𒇷", flag: "🏛️" },
  { code: "xur" as Language, name: "𒌑𒃼𒋀𒆠", flag: "🏛️" },
  { code: "cs" as Language, name: "Čeština", flag: "🇨🇿" },
  { code: "yue" as Language, name: "粵語", flag: "🇭🇰" },
  { code: "ko" as Language, name: "한국어", flag: "🇰🇷" },
  { code: "ain" as Language, name: "アイヌ・イタㇰ", flag: "🇯🇵" },
  { code: "iu" as Language, name: "ᐃᓄᐃᑦ ᓄᐃᑎᑐᑦ", flag: "🇨🇦" },
  { code: "txr" as Language, name: "𐌀𐌍𐌀 (Tartessian)", flag: "🏛️" },
  { code: "sux" as Language, name: "𒅴𒂠 (Sumerian)", flag: "🏛️" },
  { code: "xpg" as Language, name: "𐰀𐰣𐰀 (Phrygian)", flag: "🏛️" },
  { code: "xib" as Language, name: "𐌀𐌓𐌄 (Iberian)", flag: "🏛️" },
  // Caucasian & Iranian Languages
  { code: "ce" as Language, name: "Нохчийн (Chechen)", flag: "🇷🇺" },
  { code: "ttt" as Language, name: "Tat (Caucasian)", flag: "🇷🇺" },
  { code: "tly" as Language, name: "Talysh", flag: "🇮🇷" },
  { code: "av" as Language, name: "Авар (Avar)", flag: "🇷🇺" },
  { code: "lrc" as Language, name: "Luri", flag: "🇮🇷" },
  { code: "bal" as Language, name: "Baluchi", flag: "🇵🇰" },
  { code: "ia" as Language, name: "Interlingua", flag: "🌍" },
  // Ancient/Symbolic Languages (separate category)
  { code: "elx" as Language, name: "𒁹𒀭𐎠 (Elamite)", flag: "🏛️" },
  { code: "phn" as Language, name: "𐤀𐤋 (Phoenician)", flag: "🏛️" },
  { code: "lyd" as Language, name: "𐤠𐤭𐤠 (Lydian)", flag: "🏛️" },
  { code: "lyc" as Language, name: "𐊀𐊗𐊀 (Lycian)", flag: "🏛️" },
  { code: "egy" as Language, name: "𓏏𓆇𓁗 (Egyptian)", flag: "🏛️" },
  { code: "sa" as Language, name: "संस्कृतम् (Sanskrit)", flag: "🇮🇳" },
  // Additional Ancient Languages
  { code: "akk" as Language, name: "𒀝𒅗𒁺 (Akkadian)", flag: "🏛️" },
  { code: "uga" as Language, name: "𐎀𐎐 (Ugaritic)", flag: "🏛️" },
  { code: "peo" as Language, name: "𐎱𐎠𐎼𐎿 (Old Persian)", flag: "🏛️" },
  { code: "xhu" as Language, name: "𒄷𒌨𒊍 (Hurrian)", flag: "🏛️" },
  { code: "gmy" as Language, name: "𐀃𐀍𐀦 (Mycenaean)", flag: "🏛️" },
  { code: "cu" as Language, name: "ⰔⰎⰑⰂⰡ (Old Church Slavonic)", flag: "⛪" },
  { code: "got" as Language, name: "𐌲𐌿𐍄𐌹𐍃𐌺 (Gothic)", flag: "🏛️" },
  { code: "ang" as Language, name: "Ænglisc (Old English)", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { code: "non" as Language, name: "Norrǿnt mál (Old Norse)", flag: "🇳🇴" },
  { code: "xcl" as Language, name: "Գրաբար (Classical Armenian)", flag: "🇦🇲" },
  { code: "otk" as Language, name: "𐰋𐰃𐰠𐰏 (Old Turkic)", flag: "🇹🇷" },
  { code: "pal" as Language, name: "𐭯𐭠𐭫𐭮𐭩 (Pahlavi)", flag: "🇮🇷" },
  { code: "grc" as Language, name: "Ἑλληνική (Ancient Greek)", flag: "🇬🇷" },
  { code: "ave" as Language, name: "𐬀𐬬𐬈𐬯𐬙𐬀𐬥 (Avestan)", flag: "🇮🇷" },
];

export const livingLanguages = languages.filter(
  (l) => !ANCIENT_CODES.includes(l.code),
);
export const ancientLanguages = languages.filter((l) =>
  ANCIENT_CODES.includes(l.code),
);
